version: '3.8'
services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: chatbot-architecture-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_CHARSET: utf8
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: